var annotated =
[
    [ "AlgebraicStructureTraits_", "namespaceAlgebraicStructureTraits__.html", "namespaceAlgebraicStructureTraits__" ],
    [ "CGAL", null, [
      [ "Algebraic_structure_traits", "classCGAL_1_1Algebraic__structure__traits.html", null ],
      [ "Euclidean_ring_tag", "classCGAL_1_1Euclidean__ring__tag.html", null ],
      [ "Field_tag", "classCGAL_1_1Field__tag.html", null ],
      [ "Field_with_kth_root_tag", "classCGAL_1_1Field__with__kth__root__tag.html", null ],
      [ "Field_with_root_of_tag", "classCGAL_1_1Field__with__root__of__tag.html", null ],
      [ "Field_with_sqrt_tag", "classCGAL_1_1Field__with__sqrt__tag.html", null ],
      [ "Integral_domain_tag", "classCGAL_1_1Integral__domain__tag.html", null ],
      [ "Integral_domain_without_division_tag", "classCGAL_1_1Integral__domain__without__division__tag.html", null ],
      [ "Unique_factorization_domain_tag", "classCGAL_1_1Unique__factorization__domain__tag.html", null ],
      [ "Coercion_traits", "classCGAL_1_1Coercion__traits.html", "classCGAL_1_1Coercion__traits" ],
      [ "Fraction_traits", "classCGAL_1_1Fraction__traits.html", null ],
      [ "Real_embeddable_traits", "classCGAL_1_1Real__embeddable__traits.html", null ]
    ] ],
    [ "FractionTraits_", "namespaceFractionTraits__.html", "namespaceFractionTraits__" ],
    [ "RealEmbeddableTraits_", "namespaceRealEmbeddableTraits__.html", "namespaceRealEmbeddableTraits__" ],
    [ "AlgebraicStructureTraits", "classAlgebraicStructureTraits.html", "classAlgebraicStructureTraits" ],
    [ "EuclideanRing", "classEuclideanRing.html", null ],
    [ "ExplicitInteroperable", "classExplicitInteroperable.html", null ],
    [ "Field", "classField.html", "classField" ],
    [ "FieldNumberType", "classFieldNumberType.html", null ],
    [ "FieldWithKthRoot", "classFieldWithKthRoot.html", null ],
    [ "FieldWithRootOf", "classFieldWithRootOf.html", null ],
    [ "FieldWithSqrt", "classFieldWithSqrt.html", null ],
    [ "Fraction", "classFraction.html", null ],
    [ "FractionTraits", "classFractionTraits.html", "classFractionTraits" ],
    [ "FromDoubleConstructible", "classFromDoubleConstructible.html", "classFromDoubleConstructible" ],
    [ "FromIntConstructible", "classFromIntConstructible.html", "classFromIntConstructible" ],
    [ "ImplicitInteroperable", "classImplicitInteroperable.html", null ],
    [ "IntegralDomain", "classIntegralDomain.html", null ],
    [ "IntegralDomainWithoutDivision", "classIntegralDomainWithoutDivision.html", "classIntegralDomainWithoutDivision" ],
    [ "RealEmbeddable", "classRealEmbeddable.html", "classRealEmbeddable" ],
    [ "RealEmbeddableTraits", "classRealEmbeddableTraits.html", "classRealEmbeddableTraits" ],
    [ "RingNumberType", "classRingNumberType.html", null ],
    [ "UniqueFactorizationDomain", "classUniqueFactorizationDomain.html", null ]
];