var annotated =
[
    [ "ArrTraits", "namespaceArrTraits.html", "namespaceArrTraits" ],
    [ "CGAL", null, [
      [ "Arr_accessor", "classCGAL_1_1Arr__accessor.html", "classCGAL_1_1Arr__accessor" ],
      [ "Arr_algebraic_segment_traits_2", "classCGAL_1_1Arr__algebraic__segment__traits__2.html", "classCGAL_1_1Arr__algebraic__segment__traits__2" ],
      [ "Arr_Bezier_curve_traits_2", "classCGAL_1_1Arr__Bezier__curve__traits__2.html", "classCGAL_1_1Arr__Bezier__curve__traits__2" ],
      [ "Arr_circle_segment_traits_2", "classCGAL_1_1Arr__circle__segment__traits__2.html", [
        [ "Curve_2", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Curve__2.html", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Curve__2" ],
        [ "Point_2", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Point__2.html", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Point__2" ],
        [ "X_monotone_curve_2", "classCGAL_1_1Arr__circle__segment__traits__2_1_1X__monotone__curve__2.html", "classCGAL_1_1Arr__circle__segment__traits__2_1_1X__monotone__curve__2" ]
      ] ],
      [ "Arr_circular_arc_traits_2", "classCGAL_1_1Arr__circular__arc__traits__2.html", null ],
      [ "Arr_circular_line_arc_traits_2", "classCGAL_1_1Arr__circular__line__arc__traits__2.html", null ],
      [ "Arr_conic_traits_2", "classCGAL_1_1Arr__conic__traits__2.html", "classCGAL_1_1Arr__conic__traits__2" ],
      [ "Arr_consolidated_curve_data_traits_2", "classCGAL_1_1Arr__consolidated__curve__data__traits__2.html", "classCGAL_1_1Arr__consolidated__curve__data__traits__2" ],
      [ "Arr_curve_data_traits_2", "classCGAL_1_1Arr__curve__data__traits__2.html", "classCGAL_1_1Arr__curve__data__traits__2" ],
      [ "Arr_dcel_base", "classCGAL_1_1Arr__dcel__base.html", [
        [ "Arr_face_base", "classCGAL_1_1Arr__dcel__base_1_1Arr__face__base.html", null ],
        [ "Arr_halfedge_base", "classCGAL_1_1Arr__dcel__base_1_1Arr__halfedge__base.html", null ],
        [ "Arr_vertex_base", "classCGAL_1_1Arr__dcel__base_1_1Arr__vertex__base.html", null ]
      ] ],
      [ "Arr_default_dcel", "classCGAL_1_1Arr__default__dcel.html", null ],
      [ "Arr_default_overlay_traits", "classCGAL_1_1Arr__default__overlay__traits.html", null ],
      [ "Arr_face_overlay_traits", "classCGAL_1_1Arr__face__overlay__traits.html", null ],
      [ "Arr_extended_dcel", "classCGAL_1_1Arr__extended__dcel.html", null ],
      [ "Arr_extended_face", "classCGAL_1_1Arr__extended__face.html", "classCGAL_1_1Arr__extended__face" ],
      [ "Arr_extended_halfedge", "classCGAL_1_1Arr__extended__halfedge.html", "classCGAL_1_1Arr__extended__halfedge" ],
      [ "Arr_extended_vertex", "classCGAL_1_1Arr__extended__vertex.html", "classCGAL_1_1Arr__extended__vertex" ],
      [ "Arr_face_extended_dcel", "classCGAL_1_1Arr__face__extended__dcel.html", null ],
      [ "Arr_face_index_map", "classCGAL_1_1Arr__face__index__map.html", "classCGAL_1_1Arr__face__index__map" ],
      [ "Arr_landmarks_point_location", "classCGAL_1_1Arr__landmarks__point__location.html", null ],
      [ "Arr_line_arc_traits_2", "classCGAL_1_1Arr__line__arc__traits__2.html", null ],
      [ "Arr_linear_traits_2", "classCGAL_1_1Arr__linear__traits__2.html", [
        [ "Curve_2", "classCGAL_1_1Arr__linear__traits__2_1_1Curve__2.html", "classCGAL_1_1Arr__linear__traits__2_1_1Curve__2" ]
      ] ],
      [ "Arr_naive_point_location", "classCGAL_1_1Arr__naive__point__location.html", null ],
      [ "Arr_non_caching_segment_basic_traits_2", "classCGAL_1_1Arr__non__caching__segment__basic__traits__2.html", null ],
      [ "Arr_non_caching_segment_traits_2", "classCGAL_1_1Arr__non__caching__segment__traits__2.html", null ],
      [ "Arr_observer", "classCGAL_1_1Arr__observer.html", "classCGAL_1_1Arr__observer" ],
      [ "Arr_point_location_result", "classCGAL_1_1Arr__point__location__result.html", "classCGAL_1_1Arr__point__location__result" ],
      [ "Arr_polycurve_traits_2", "classCGAL_1_1Arr__polycurve__traits__2.html", "classCGAL_1_1Arr__polycurve__traits__2" ],
      [ "Arr_polyline_traits_2", "classCGAL_1_1Arr__polyline__traits__2.html", "classCGAL_1_1Arr__polyline__traits__2" ],
      [ "Arr_rational_function_traits_2", "classCGAL_1_1Arr__rational__function__traits__2.html", "classCGAL_1_1Arr__rational__function__traits__2" ],
      [ "Arr_segment_traits_2", "classCGAL_1_1Arr__segment__traits__2.html", null ],
      [ "Arr_oblivious_side_tag", "classCGAL_1_1Arr__oblivious__side__tag.html", null ],
      [ "Arr_open_side_tag", "classCGAL_1_1Arr__open__side__tag.html", null ],
      [ "Arr_trapezoid_ric_point_location", "classCGAL_1_1Arr__trapezoid__ric__point__location.html", "classCGAL_1_1Arr__trapezoid__ric__point__location" ],
      [ "Arr_vertex_index_map", "classCGAL_1_1Arr__vertex__index__map.html", "classCGAL_1_1Arr__vertex__index__map" ],
      [ "Arr_walk_along_line_point_location", "classCGAL_1_1Arr__walk__along__line__point__location.html", null ],
      [ "Arrangement_2", "classCGAL_1_1Arrangement__2.html", "classCGAL_1_1Arrangement__2" ],
      [ "Arrangement_with_history_2", "classCGAL_1_1Arrangement__with__history__2.html", "classCGAL_1_1Arrangement__with__history__2" ],
      [ "Arr_extended_dcel_text_formatter", "classCGAL_1_1Arr__extended__dcel__text__formatter.html", null ],
      [ "Arr_face_extended_text_formatter", "classCGAL_1_1Arr__face__extended__text__formatter.html", null ],
      [ "Arr_text_formatter", "classCGAL_1_1Arr__text__formatter.html", null ],
      [ "Arr_with_history_text_formatter", "classCGAL_1_1Arr__with__history__text__formatter.html", null ]
    ] ],
    [ "ArrangementApproximateTraits_2", "classArrangementApproximateTraits__2.html", "classArrangementApproximateTraits__2" ],
    [ "ArrangementBasicTraits_2", "classArrangementBasicTraits__2.html", "classArrangementBasicTraits__2" ],
    [ "ArrangementConstructXMonotoneCurveTraits_2", "classArrangementConstructXMonotoneCurveTraits__2.html", "classArrangementConstructXMonotoneCurveTraits__2" ],
    [ "ArrangementDcel", "classArrangementDcel.html", "classArrangementDcel" ],
    [ "ArrangementDcelFace", "classArrangementDcelFace.html", "classArrangementDcelFace" ],
    [ "ArrangementDcelHalfedge", "classArrangementDcelHalfedge.html", "classArrangementDcelHalfedge" ],
    [ "ArrangementDcelHole", "classArrangementDcelHole.html", "classArrangementDcelHole" ],
    [ "ArrangementDcelIsolatedVertex", "classArrangementDcelIsolatedVertex.html", "classArrangementDcelIsolatedVertex" ],
    [ "ArrangementDcelVertex", "classArrangementDcelVertex.html", "classArrangementDcelVertex" ],
    [ "ArrangementDcelWithRebind", "classArrangementDcelWithRebind.html", "classArrangementDcelWithRebind" ],
    [ "ArrangementInputFormatter", "classArrangementInputFormatter.html", "classArrangementInputFormatter" ],
    [ "ArrangementLandmarkTraits_2", "classArrangementLandmarkTraits__2.html", null ],
    [ "ArrangementOpenBoundaryTraits_2", "classArrangementOpenBoundaryTraits__2.html", "classArrangementOpenBoundaryTraits__2" ],
    [ "ArrangementOutputFormatter", "classArrangementOutputFormatter.html", "classArrangementOutputFormatter" ],
    [ "ArrangementPointLocation_2", "classArrangementPointLocation__2.html", "classArrangementPointLocation__2" ],
    [ "ArrangementTraits_2", "classArrangementTraits__2.html", "classArrangementTraits__2" ],
    [ "ArrangementVerticalRayShoot_2", "classArrangementVerticalRayShoot__2.html", "classArrangementVerticalRayShoot__2" ],
    [ "ArrangementWithHistoryInputFormatter", "classArrangementWithHistoryInputFormatter.html", "classArrangementWithHistoryInputFormatter" ],
    [ "ArrangementWithHistoryOutputFormatter", "classArrangementWithHistoryOutputFormatter.html", "classArrangementWithHistoryOutputFormatter" ],
    [ "ArrangementXMonotoneTraits_2", "classArrangementXMonotoneTraits__2.html", "classArrangementXMonotoneTraits__2" ],
    [ "ArrTrimTraits_2", "classArrTrimTraits__2.html", "classArrTrimTraits__2" ],
    [ "OverlayTraits", "classOverlayTraits.html", "classOverlayTraits" ]
];